name: Deploy to Genezio

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker image
        run: |
          docker build -t fastapi-app .

      - name: Log in to Genezio
        run: |
          docker login -u ${{ secrets.GENEZIO_USERNAME }} -p ${{ secrets.GENEZIO_PASSWORD }} registry.genezio.com

      - name: Push Docker image to Genezio registry
        run: |
          docker tag fastapi-app registry.genezio.com/yourusername/fastapi-app:latest
          docker push registry.genezio.com/yourusername/fastapi-app:latest

      - name: Deploy to Genezio
        run: |
          curl -X POST https://api.genezio.com/deploy \
          -H "Authorization: Bearer ${{ secrets.GENEZIO_API_TOKEN }}" \
          -d '{"image": "registry.genezio.com/yourusername/fastapi-app:latest", "service": "fastapi-service"}'
